package com.redslovesgames.tideborne.fishing.gear;

import static org.junit.jupiter.api.Assertions.*;
import net.minecraft.util.Identifier;
import org.junit.jupiter.api.Test;

class FishingGearRegistryTest {
 @Test void everySupportedFishingGearIdHasOneCanonicalProfile(){
  assertProfile("tide:copper_line",FishingGearRegistry.GearProfile.TIDE_COPPER_LINE);assertProfile("tide:iron_line",FishingGearRegistry.GearProfile.TIDE_IRON_LINE);assertProfile("tide:golden_line",FishingGearRegistry.GearProfile.TIDE_GOLDEN_LINE);assertProfile("tide:diamond_line",FishingGearRegistry.GearProfile.TIDE_DIAMOND_LINE);assertProfile("tidebound_compatibility:tentacle_line",FishingGearRegistry.GearProfile.TENTACLE_LINE);assertProfile("tidebound_compatibility:swift_line",FishingGearRegistry.GearProfile.SWIFT_LINE);assertProfile("tidebound_compatibility:copper_leader",FishingGearRegistry.GearProfile.COPPER_LEADER);assertProfile("tidebound_compatibility:steel_leader",FishingGearRegistry.GearProfile.IRON_LEADER);assertProfile("tidebound_compatibility:gold_leader",FishingGearRegistry.GearProfile.GOLD_LEADER);assertProfile("tidebound_compatibility:diamond_leader",FishingGearRegistry.GearProfile.DIAMOND_LEADER);assertProfile("tidebound_compatibility:seafarers_hook",FishingGearRegistry.GearProfile.SEAFARERS_HOOK);assertProfile("tidebound_compatibility:shark_tooth_hook",FishingGearRegistry.GearProfile.SHARK_TOOTH_HOOK);assertProfile("tidebound_compatibility:kujira_bone_fishing_rod",FishingGearRegistry.GearProfile.KUJIRA_BONE_FISHING_ROD);assertProfile("tidebound_compatibility:leviathan_bait",FishingGearRegistry.GearProfile.LEVIATHAN_BAIT);assertEquals(FishingGearRegistry.GearProfile.values().length,FishingGearRegistry.profiles().size());}
 @Test void everyCanonicalProfileReversesToSameId(){for(var p:FishingGearRegistry.GearProfile.values()){Identifier id=FishingGearRegistry.registeredId(p).orElseThrow();assertEquals(p,FishingGearRegistry.resolveId(id).orElseThrow());assertEquals(p.itemId(),id);}}
 @Test void currentTideBobbersAreExactCanonicalGearIdentities(){assertEquals(32,FishingGearRegistry.supportedBobberIds().size());assertTrue(FishingGearRegistry.isSupportedBobberId(Identifier.of("tide:red_bobber")));assertTrue(FishingGearRegistry.isSupportedBobberId(Identifier.of("tide:enchanted_golden_apple_bobber")));assertEquals(FishingGearRegistry.Slot.BOBBER,FishingGearRegistry.resolveSlot(Identifier.of("tide:diamond_bobber")).orElseThrow());}
 @Test void unregisteredLookalikesCannotInherit(){assertTrue(FishingGearRegistry.resolveId(Identifier.of("othermod","diamond_line")).isEmpty());assertTrue(FishingGearRegistry.resolveSlot(Identifier.of("othermod","heart_bobber")).isEmpty());}
 @Test void profilesExposeMetadata(){assertEquals(FishingGearRegistry.Origin.TIDE,FishingGearRegistry.GearProfile.TIDE_DIAMOND_LINE.origin());assertEquals(FishingGearRegistry.Slot.ATTACHMENT,FishingGearRegistry.GearProfile.DIAMOND_LEADER.slot());}
 private static void assertProfile(String id,FishingGearRegistry.GearProfile expected){Identifier parsed=Identifier.of(id);assertEquals(expected,FishingGearRegistry.resolveId(parsed).orElseThrow());assertEquals(parsed,FishingGearRegistry.registeredId(expected).orElseThrow());}
}
