#!/usr/bin/env python3
"""Delta-aware quality report aggregator for Tideborne Java changes.

The external analyzers deliberately scan with enough context to be useful:
- PMD may scan the whole production tree.
- CPD scans the whole production tree so a new block can match old code.
- Semgrep performs its own baseline comparison.

This script gates only findings that intersect Java lines changed since the
selected baseline, so existing repository debt does not become a blocker just
because a file is present in the checkout.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
import xml.etree.ElementTree as ET
from dataclasses import dataclass, asdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
JAVA_ROOT = "src/main/java"
AI_META_RE = re.compile(
    r"(?i)(?:ai[- ]generated|llm[- ]generated|agent[- ]generated|"
    r"generated by (?:chatgpt|claude|codex|copilot)|coding agent)"
)
NARRATIVE_RE = re.compile(
    r"(?i)^\s*(?://|\*)\s*(?:phase\s+\d+\b|step\s+\d+\b|"
    r"this (?:method|class|function) (?:simply|just)\b|"
    r"(?:first|then|finally),?\s+we\b)"
)


@dataclass
class Finding:
    tool: str
    rule: str
    path: str
    line: int
    message: str
    blocking: bool = True


def run_git(*args: str, check: bool = True) -> str:
    proc = subprocess.run(
        ["git", *args],
        cwd=ROOT,
        text=True,
        capture_output=True,
    )
    if check and proc.returncode != 0:
        raise SystemExit(proc.stderr.strip() or f"git {' '.join(args)} failed")
    return proc.stdout


def normalize_path(raw: str) -> str:
    value = raw.replace("\\", "/")
    if value.startswith("file://"):
        value = value[7:]
    marker = f"{JAVA_ROOT}/"
    if marker in value:
        return marker + value.split(marker, 1)[1]
    try:
        return str(Path(value).resolve().relative_to(ROOT.resolve())).replace("\\", "/")
    except Exception:
        return value.lstrip("./")


def changed_line_map(base: str) -> dict[str, set[int]]:
    """Return new-side line numbers changed between base and HEAD."""
    diff = run_git(
        "diff",
        "--unified=0",
        "--no-color",
        f"{base}..HEAD",
        "--",
        JAVA_ROOT,
    )
    changed: dict[str, set[int]] = {}
    current: str | None = None
    for raw in diff.splitlines():
        if raw.startswith("+++ "):
            target = raw[4:].strip()
            if target == "/dev/null":
                current = None
            else:
                current = target[2:] if target.startswith("b/") else target
                changed.setdefault(current, set())
            continue
        if current and raw.startswith("@@"):
            match = re.search(r"\+(\d+)(?:,(\d+))?", raw)
            if not match:
                continue
            start = int(match.group(1))
            count = int(match.group(2) or "1")
            if count > 0:
                changed[current].update(range(start, start + count))
    return {path: lines for path, lines in changed.items() if lines}


def intersects(changed: dict[str, set[int]], path: str, start: int, end: int | None = None) -> bool:
    lines = changed.get(normalize_path(path))
    if not lines:
        return False
    finish = end if end is not None and end >= start else start
    return any(line in lines for line in range(start, finish + 1))


def sarif_results(path: Path, tool: str, changed: dict[str, set[int]], *, baseline_filtered: bool = False) -> list[Finding]:
    if not path.exists():
        return []
    data = json.loads(path.read_text(encoding="utf-8"))
    findings: list[Finding] = []
    for run in data.get("runs", []):
        for result in run.get("results", []):
            locations = result.get("locations") or []
            if not locations:
                continue
            physical = locations[0].get("physicalLocation", {})
            artifact = physical.get("artifactLocation", {})
            region = physical.get("region", {})
            raw_path = artifact.get("uri", "")
            line = int(region.get("startLine", 1) or 1)
            end = int(region.get("endLine", line) or line)
            if not baseline_filtered and not intersects(changed, raw_path, line, end):
                continue
            if baseline_filtered and changed and not intersects(changed, raw_path, line, end):
                # Semgrep already performs baseline comparison. The second check
                # keeps stale/non-diff results from becoming blockers.
                continue
            message_obj = result.get("message", {})
            message = message_obj.get("text") or message_obj.get("markdown") or "Static-analysis finding"
            findings.append(
                Finding(
                    tool=tool,
                    rule=str(result.get("ruleId") or "unknown"),
                    path=normalize_path(raw_path),
                    line=line,
                    message=" ".join(str(message).split()),
                )
            )
    return findings


def strip_xml_namespace(root: ET.Element) -> None:
    for elem in root.iter():
        if "}" in elem.tag:
            elem.tag = elem.tag.split("}", 1)[1]


def cpd_findings(path: Path, changed: dict[str, set[int]]) -> list[Finding]:
    if not path.exists():
        return []
    root = ET.parse(path).getroot()
    strip_xml_namespace(root)
    findings: list[Finding] = []
    for dup in root.findall(".//duplication"):
        files = dup.findall("file")
        if len(files) < 2:
            continue
        touched = []
        for file_elem in files:
            raw_path = file_elem.attrib.get("path", "")
            start = int(file_elem.attrib.get("line", "1"))
            end = int(file_elem.attrib.get("endline", start))
            if intersects(changed, raw_path, start, end):
                touched.append((raw_path, start))
        if not touched:
            continue
        lines = dup.attrib.get("lines", "?")
        tokens = dup.attrib.get("tokens", "?")
        peers = ", ".join(
            f"{normalize_path(f.attrib.get('path', ''))}:{f.attrib.get('line', '?')}"
            for f in files[:5]
        )
        for raw_path, start in touched:
            findings.append(
                Finding(
                    tool="CPD",
                    rule="new-duplicate-block",
                    path=normalize_path(raw_path),
                    line=start,
                    message=f"Changed code participates in a {lines}-line/{tokens}-token duplicate block ({peers}).",
                )
            )
    return findings


def comment_findings(changed: dict[str, set[int]]) -> tuple[list[Finding], list[Finding]]:
    blockers: list[Finding] = []
    warnings: list[Finding] = []
    for path, line_numbers in changed.items():
        file_path = ROOT / path
        if not file_path.exists():
            continue
        lines = file_path.read_text(encoding="utf-8", errors="replace").splitlines()
        for line_no in sorted(line_numbers):
            if line_no < 1 or line_no > len(lines):
                continue
            text = lines[line_no - 1]
            if AI_META_RE.search(text):
                blockers.append(
                    Finding(
                        tool="Tideborne",
                        rule="ai-process-comment",
                        path=path,
                        line=line_no,
                        message="Remove AI/agent-generation process commentary from production Java.",
                    )
                )
            elif NARRATIVE_RE.search(text):
                warnings.append(
                    Finding(
                        tool="Tideborne",
                        rule="narrative-comment",
                        path=path,
                        line=line_no,
                        message="Review narrative/process-style comment; keep it only if it explains a real invariant or compatibility reason.",
                        blocking=False,
                    )
                )
    return blockers, warnings


def tool_missing(path: Path, name: str, changed: dict[str, set[int]]) -> list[Finding]:
    if not changed or path.exists():
        return []
    return [
        Finding(
            tool=name,
            rule="missing-report",
            path=str(path),
            line=1,
            message=f"{name} report was not produced for a Java-changing revision.",
        )
    ]


def render_markdown(report: dict) -> str:
    lines = [
        "# Tideborne Java / AI quality gate",
        "",
        f"- status: **{report['status']}**",
        f"- base: `{report['base']}`",
        f"- head: `{report['head']}`",
        f"- changed production Java files: **{report['changed_java_files']}**",
        f"- changed production Java lines: **{report['changed_java_lines']}**",
        f"- blocking findings: **{len(report['blocking_findings'])}**",
        f"- advisory findings: **{len(report['warnings'])}**",
        "",
    ]
    if report["blocking_findings"]:
        lines += ["## Blocking findings", ""]
        for item in report["blocking_findings"][:100]:
            lines.append(
                f"- **{item['tool']} / {item['rule']}** — `{item['path']}:{item['line']}` — {item['message']}"
            )
        lines.append("")
    if report["warnings"]:
        lines += ["## Advisory findings", ""]
        for item in report["warnings"][:100]:
            lines.append(
                f"- **{item['tool']} / {item['rule']}** — `{item['path']}:{item['line']}` — {item['message']}"
            )
        lines.append("")
    if not report["blocking_findings"] and not report["warnings"]:
        lines += ["No new changed-line findings were reported.", ""]
    lines += [
        "## Continuation rule",
        "",
        "Fix only findings introduced by the current diff. Do not broad-clean unrelated historical code to satisfy this gate.",
        "",
    ]
    return "\n".join(lines)


def commit_exists(sha: str) -> bool:
    proc = subprocess.run(
        ["git", "cat-file", "-e", f"{sha}^{{commit}}"],
        cwd=ROOT,
        text=True,
        capture_output=True,
    )
    return proc.returncode == 0


def resolve_base(default_branch: str) -> str:
    event_name = os.environ.get("GITHUB_EVENT_NAME", "")
    ref_name = os.environ.get("GITHUB_REF_NAME", "")
    event: dict = {}
    event_path = os.environ.get("GITHUB_EVENT_PATH")
    if event_path and Path(event_path).exists():
        event = json.loads(Path(event_path).read_text(encoding="utf-8"))

    if event_name == "pull_request":
        base = str(event.get("pull_request", {}).get("base", {}).get("sha", "")).strip()
        if base and commit_exists(base):
            return base

    if event_name == "push" and ref_name == default_branch:
        before = str(event.get("before", "")).strip()
        if before and set(before) != {"0"} and commit_exists(before):
            return before

    fetch = subprocess.run(
        ["git", "fetch", "--no-tags", "origin", default_branch],
        cwd=ROOT,
        text=True,
        capture_output=True,
    )
    if fetch.returncode == 0:
        remote_head = run_git("rev-parse", "FETCH_HEAD").strip()
        base = run_git("merge-base", "HEAD", remote_head).strip()
    else:
        base = run_git("rev-parse", "HEAD^").strip()

    head = run_git("rev-parse", "HEAD").strip()
    if base == head:
        parent = subprocess.run(
            ["git", "rev-parse", "HEAD^"],
            cwd=ROOT,
            text=True,
            capture_output=True,
        )
        if parent.returncode == 0:
            base = parent.stdout.strip()
    return base


def resolve_base_command(args: argparse.Namespace) -> int:
    base = resolve_base(args.default_branch)
    print(base)
    github_output = os.environ.get("GITHUB_OUTPUT")
    if github_output:
        with open(github_output, "a", encoding="utf-8") as handle:
            handle.write(f"sha={base}\n")
    return 0


def analyze(args: argparse.Namespace) -> int:
    base = args.base
    changed = changed_line_map(base)
    blockers: list[Finding] = []
    warnings: list[Finding] = []

    pmd_path = ROOT / args.pmd
    cpd_path = ROOT / args.cpd
    semgrep_path = ROOT / args.semgrep

    blockers.extend(tool_missing(pmd_path, "PMD", changed))
    blockers.extend(tool_missing(cpd_path, "CPD", changed))
    blockers.extend(tool_missing(semgrep_path, "Semgrep", changed))

    blockers.extend(sarif_results(pmd_path, "PMD", changed))
    blockers.extend(cpd_findings(cpd_path, changed))
    blockers.extend(sarif_results(semgrep_path, "Semgrep", changed, baseline_filtered=True))

    comment_blockers, comment_warnings = comment_findings(changed)
    blockers.extend(comment_blockers)
    warnings.extend(comment_warnings)

    blockers.sort(key=lambda f: (f.path, f.line, f.tool, f.rule))
    warnings.sort(key=lambda f: (f.path, f.line, f.tool, f.rule))

    report = {
        "schema_version": 1,
        "status": "FAIL" if blockers else "PASS",
        "base": base,
        "head": run_git("rev-parse", "HEAD").strip(),
        "changed_java_files": len(changed),
        "changed_java_lines": sum(len(lines) for lines in changed.values()),
        "changed_files": sorted(changed),
        "blocking_findings": [asdict(f) for f in blockers],
        "warnings": [asdict(f) for f in warnings],
    }

    json_path = ROOT / args.json
    markdown_path = ROOT / args.markdown
    json_path.parent.mkdir(parents=True, exist_ok=True)
    markdown_path.parent.mkdir(parents=True, exist_ok=True)
    json_path.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    markdown_path.write_text(render_markdown(report), encoding="utf-8")

    print(render_markdown(report))
    return 1 if blockers else 0


def main() -> None:
    parser = argparse.ArgumentParser()
    sub = parser.add_subparsers(dest="command", required=True)

    base_parser = sub.add_parser("resolve-base", help="resolve the delta baseline for GitHub Actions")
    base_parser.add_argument("--default-branch", default="dev")

    analyze_parser = sub.add_parser("analyze", help="aggregate delta-aware analyzer reports")
    analyze_parser.add_argument("--base", required=True)
    analyze_parser.add_argument("--pmd", default="pmd-report.sarif")
    analyze_parser.add_argument("--cpd", default="build/quality-gate/cpd.xml")
    analyze_parser.add_argument("--semgrep", default="build/quality-gate/semgrep.sarif")
    analyze_parser.add_argument("--json", default="build/quality-gate/report.json")
    analyze_parser.add_argument("--markdown", default="build/quality-gate/report.md")

    args = parser.parse_args()
    if args.command == "resolve-base":
        raise SystemExit(resolve_base_command(args))
    if args.command == "analyze":
        raise SystemExit(analyze(args))


if __name__ == "__main__":
    main()
